# Generated by Django 3.0.7 on 2020-07-10 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'App visit'), (2, 'Post view')], db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ua', models.CharField(blank=True, max_length=1000)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('hash', models.CharField(blank=True, db_index=True, max_length=50)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Post')),
            ],
        ),
    ]
